import ArrowForwardIcon from '@mui/icons-material/ArrowForward'
import CheckCircleOutlineIcon from '@mui/icons-material/CheckCircleOutline'
import { Box, Button, Container, Grid, Paper, Stack, Typography } from '@mui/material'
import { Link as RouterLink } from 'react-router-dom'
import { PublicHeader } from '../components/PublicHeader'

export function HomePage() {
  return <Box minHeight="100vh" bgcolor="background.default"><PublicHeader /><Container maxWidth="lg"><Grid container spacing={7} alignItems="center" sx={{ py: { xs: 7, md: 12 } }}><Grid size={{ xs: 12, md: 7 }}><Typography variant="overline" color="secondary.main" fontWeight={800} letterSpacing=".14em">Physical therapy, connected</Typography><Typography variant="h1" sx={{ fontSize: { xs: '2.8rem', md: '4.5rem' }, mt: 1, mb: 3 }}>Move patients forward.</Typography><Typography variant="h6" color="text.secondary" fontWeight={400} lineHeight={1.6} maxWidth={600}>Milestone brings patient progress, appointments, and communication into one clear workspace built for physical therapists and their care teams.</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} mt={4}><Button component={RouterLink} to="/login" variant="contained" size="large" endIcon={<ArrowForwardIcon />}>Enter therapist portal</Button><Button component={RouterLink} to="/request-access" variant="outlined" size="large">Request access</Button></Stack></Grid><Grid size={{ xs: 12, md: 5 }}><Paper sx={{ p: { xs: 3, md: 4 }, bgcolor: 'primary.dark', color: 'white', border: 0, borderRadius: 5 }}><Typography variant="h5" fontWeight={700} mb={3}>Everything in one view</Typography>{['Patient progress overview', 'Secure team communication', 'A calmer clinic workflow'].map((item) => <Stack direction="row" spacing={1.5} alignItems="center" key={item} mb={2}><CheckCircleOutlineIcon color="secondary" /><Typography>{item}</Typography></Stack>)}<Box sx={{ height: 8, bgcolor: 'secondary.main', borderRadius: 10, mt: 4, width: '55%' }} /></Paper></Grid></Grid></Container></Box>
}
